window.alarmConfig = {
  categories: [
    {
      name: "Kreislauf",
      keywords: [
        { word: "Kreislauferkrankung, allgemein", resources: ["RES1", "RES2"] },
        { word: "Exsikkose", resources: ["RES1", "RES2"] },
        { word: "Kreislaufprobleme", resources: ["RES1", "RES2"] },
        { word: "Hypertensive Entgleisung", resources: ["RES1", "RES2"] },
        { word: "Hypotone Entgleisung", resources: ["RES1", "RES2"] },
        { word: "Kardiale Notfälle, allgemein", resources: ["RES1", "RES2"] },
        { word: "Akuter Thoraxschmerz", resources: ["RES1", "RES2"] },
        { word: "Akutes Koronarsyndrom", resources: ["RES1", "RES2"] },
        { word: "Herzinsuffizienz", resources: ["RES1", "RES2"] },
        { word: "Herzrhythmusstörung, allgemein", resources: ["RES1", "RES2"] },
        {
          word: "Herzrhythmusstörung, Bradykardie",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Herzrhythmusstörung, Tachykardie",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Reanimation",
          resources: ["Trupp", "RTW", "NEF", "Info an ASL"],
        },
        {
          word: "Allergische Reaktion, allgemein",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Allergische Reaktion, Insektengifte",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Allergische Reaktion, Lebensmittel",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Allergische Reaktion, Medikamente",
          resources: ["RES1", "RES2"],
        },
        { word: "Anaphylaktischer Schock", resources: ["RES1", "RES2"] },
        { word: "Thermische Notfälle, allgemein", resources: ["RES1", "RES2"] },
        { word: "Erfrierung", resources: ["RES1", "RES2"] },
        { word: "Sonnenstich", resources: ["RES1", "RES2"] },
        { word: "Unterkühlung", resources: ["RES1", "RES2"] },
        { word: "Verbrennung", resources: ["RES1", "RES2"] },
        { word: "Verbrühung", resources: ["RES1", "RES2"] },
        {
          word: "sonstiger kardiologischer Notfall",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Atmung",
      keywords: [
        { word: "Atemnot, allgemein", resources: ["RES1", "RES2"] },
        { word: "Aspiration / Bolusgeschehen", resources: ["RES1", "RES2"] },
        { word: "Asthma bronchiale", resources: ["RES1", "RES2"] },
        { word: "Atemnot, akut", resources: ["RES1", "RES2"] },
        { word: "COPD", resources: ["RES1", "RES2"] },
        { word: "Ertrinken", resources: ["RES1", "RES2"] },
        { word: "Hyperventilation", resources: ["RES1", "RES2"] },
        { word: "Lungenembolie", resources: ["RES1", "RES2"] },
        { word: "Lungenödem", resources: ["RES1", "RES2"] },
        { word: "Pneumonie", resources: ["RES1", "RES2"] },
        {
          word: "Pneumothorax / Spannungspneumothorax",
          resources: ["RES1", "RES2"],
        },
        {
          word: "sonstiger respiratorischer Notfall",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Neurologie / Bewusstsein",
      keywords: [
        { word: "Bewusstseinsstörung, allgemein", resources: ["RES1", "RES2"] },
        { word: "Apoplex / TIA / PRIND", resources: ["RES1", "RES2"] },
        { word: "Hyperglykämie", resources: ["RES1", "RES2"] },
        { word: "Hypoglykämie", resources: ["RES1", "RES2"] },
        { word: "Krampfanfall", resources: ["RES1", "RES2"] },
        { word: "Person bedingt ansprechbar", resources: ["RES1", "RES2"] },
        { word: "Unklare Bewusstlosigkeit", resources: ["RES1", "RES2"] },
        {
          word: "Kollabierte Person, ansprechbar",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Kollabierte Person, nicht ansprechbar",
          resources: ["RES1", "RES2"],
        },
        {
          word: "sonstiger neurologischer Notfall",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Abdomen",
      keywords: [
        { word: "Abdomen, akut", resources: ["RES1", "RES2"] },
        { word: "Abdomen, unklar", resources: ["RES1", "RES2"] },
        { word: "Blinddarmentzündung", resources: ["RES1", "RES2"] },
        { word: "Harnverhalt", resources: ["RES1", "RES2"] },
        { word: "Ileus nft", resources: ["RES1", "RES2"] },
        { word: "Magenblutung / Darmblutung", resources: ["RES1", "RES2"] },
        { word: "Nierenkolik / Gallenkolik", resources: ["RES1", "RES2"] },
        { word: "sonstiger abdomineller Notfall", resources: ["RES1", "RES2"] },
      ],
    },
    {
      name: "Allgemeine Erkrankungen",
      keywords: [
        { word: "Erkrankung allgemein", resources: ["RES1", "RES2"] },
        { word: "Abusus C2H5OH", resources: ["RES1", "RES2"] },
        { word: "Thrombose / Gefäßverschluss", resources: ["RES1", "RES2"] },
        { word: "Bandscheibenprolaps / Lumbago", resources: ["RES1", "RES2"] },
        { word: "Infekt – fieberhaft", resources: ["RES1", "RES2"] },
        { word: "Hilflose Person", resources: ["RES1", "RES2"] },
        { word: "HNO", resources: ["RES1", "RES2"] },
        { word: "Nasenbluten, unstillbar", resources: ["RES1", "RES2"] },
        { word: "Psychischer Ausnahmezustand", resources: ["RES1", "RES2"] },
        { word: "Schlechter AZ", resources: ["RES1", "RES2"] },
        { word: "Schmerzzustand", resources: ["RES1", "RES2"] },
        { word: "Tumorleiden", resources: ["RES1", "RES2"] },
        { word: "sonstiger Notfall", resources: ["RES1", "RES2"] },
      ],
    },
    {
      name: "Intoxikation",
      keywords: [
        { word: "Intoxikation, allgemein", resources: ["RES1", "RES2"] },
        { word: "Intoxikation, Alkohol", resources: ["RES1", "RES2"] },
        {
          word: "Intoxikation, Atemgifte / Rauchgase",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Intoxikation, Drogen / Rauschgifte",
          resources: ["RES1", "RES2"],
        },
        { word: "Intoxikation, Medikamente", resources: ["RES1", "RES2"] },
        {
          word: "Intoxikation, Mischintoxikation",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Suizid",
      keywords: [
        { word: "Suizid, allgemein", resources: ["RES1", "RES2"] },
        { word: "Suizid, Androhung", resources: ["RES1", "RES2"] },
      ],
    },
    {
      name: "Trauma",
      keywords: [
        { word: "Trauma, allgemein", resources: ["RES1", "RES2"] },
        { word: "Trauma, schwer", resources: ["RES1", "RES2"] },
        { word: "Abdominaltrauma", resources: ["RES1", "RES2"] },
        { word: "Extremitätentrauma", resources: ["RES1", "RES2"] },
        { word: "Gesichtsschädeltrauma", resources: ["RES1", "RES2"] },
        { word: "Inhalationstrauma", resources: ["RES1", "RES2"] },
        { word: "Polytrauma", resources: ["RES1", "RES2"] },
        { word: "Schädel-Hirn-Trauma", resources: ["RES1", "RES2"] },
        { word: "Thoraxtrauma", resources: ["RES1", "RES2"] },
        { word: "Wirbelsäulentrauma", resources: ["RES1", "RES2"] },
        {
          word: "sonstiger traumatologischer Notfall",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Extremitäten",
      keywords: [
        { word: "Amputationsverletzung", resources: ["RES1", "RES2"] },
        { word: "Armverletzung", resources: ["RES1", "RES2"] },
        { word: "Augenverletzung", resources: ["RES1", "RES2"] },
        { word: "Beckenverletzung", resources: ["RES1", "RES2"] },
        { word: "Beinverletzung", resources: ["RES1", "RES2"] },
        { word: "Blutung, leicht", resources: ["RES1", "RES2"] },
        { word: "Blutung, stark", resources: ["RES1", "RES2"] },
        { word: "Fußverletzung", resources: ["RES1", "RES2"] },
        { word: "Gesichtsverletzung", resources: ["RES1", "RES2"] },
        { word: "Handverletzung", resources: ["RES1", "RES2"] },
        { word: "Kopfverletzung", resources: ["RES1", "RES2"] },
        { word: "Knieverletzung", resources: ["RES1", "RES2"] },
        { word: "Oberarmverletzung", resources: ["RES1", "RES2"] },
        { word: "Oberschenkelhalsverletzung", resources: ["RES1", "RES2"] },
        { word: "Oberschenkelverletzung", resources: ["RES1", "RES2"] },
        { word: "Pfählungsverletzung", resources: ["RES1", "RES2"] },
        { word: "Rippenverletzung", resources: ["RES1", "RES2"] },
        { word: "Schnittverletzung", resources: ["RES1", "RES2"] },
        { word: "Schussverletzung", resources: ["RES1", "RES2"] },
        { word: "Sprunggelenksverletzung", resources: ["RES1", "RES2"] },
        { word: "Stichverletzung", resources: ["RES1", "RES2"] },
        { word: "Teilamputationsverletzung", resources: ["RES1", "RES2"] },
        { word: "Tierbissverletzung", resources: ["RES1", "RES2"] },
        { word: "Unterarmverletzung", resources: ["RES1", "RES2"] },
        { word: "Unterschenkelverletzung", resources: ["RES1", "RES2"] },
        { word: "Verätzung Säuren / Laugen", resources: ["RES1", "RES2"] },
        { word: "Volumenmangelschock", resources: ["RES1", "RES2"] },
      ],
    },
    {
      name: "Pädiatrie / Gynäkologie",
      keywords: [
        {
          word: "Pädiatrischer Notfall, allgemein",
          resources: ["RES1", "RES2"],
        },
        { word: "Epiglottitis / Pseudokrupp", resources: ["RES1", "RES2"] },
        { word: "Fieberkrampf", resources: ["RES1", "RES2"] },
        {
          word: "Urologischer Notfall, allgemein",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Gynäkologischer Notfall, allgemein",
          resources: ["RES1", "RES2"],
        },
        { word: "Entbindung, Kliniktransport", resources: ["RES1", "RES2"] },
        { word: "Frühgeburt", resources: ["RES1", "RES2"] },
        { word: "Geburt, einsetzend", resources: ["RES1", "RES2"] },
        { word: "Vaginale Blutung", resources: ["RES1", "RES2"] },
        { word: "Fruchtwasserabgang", resources: ["RES1", "RES2"] },
        {
          word: "sonstiger pädiatrischer Notfall",
          resources: ["RES1", "RES2"],
        },
        {
          word: "sonstiger gynäkologischer Notfall",
          resources: ["RES1", "RES2"],
        },
      ],
    },
    {
      name: "Unfälle",
      keywords: [
        { word: "Badeunfall", resources: ["RES1", "RES2"] },
        { word: "Betriebs-/Arbeitsunfall", resources: ["RES1", "RES2"] },
        { word: "Hausunfall", resources: ["RES1", "RES2"] },
        {
          word: "Inlineskaterunfall / Skaterunfall",
          resources: ["RES1", "RES2"],
        },
        { word: "Körperverletzung", resources: ["RES1", "RES2"] },
        { word: "Reitunfall", resources: ["RES1", "RES2"] },
        { word: "Schulunfall", resources: ["RES1", "RES2"] },
        { word: "Sportunfall", resources: ["RES1", "RES2"] },
        {
          word: "Stromunfall Niederspannung <1000V",
          resources: ["RES1", "RES2"],
        },
        {
          word: "Stromunfall Hochspannung >1000V",
          resources: ["RES1", "RES2"],
        },
        { word: "Sturz aus Höhe < 3 Meter", resources: ["RES1", "RES2"] },
        { word: "Sturz aus Höhe > 3 Meter", resources: ["RES1", "RES2"] },
        { word: "Tauchunfall", resources: ["RES1", "RES2"] },
        { word: "Treppensturz", resources: ["RES1", "RES2"] },
        { word: "Verkehrsunfall, allgemein", resources: ["RES1", "RES2"] },
      ],
    },
  ],
};
