name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: System-Dependencies für Puppeteer
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-6 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libxss1

      - name: Create reports directory
        run: mkdir -p reports

      - name: Unit- und Logic-Tests
        run: npm test

      - name: End-to-End Tests mit Puppeteer
        run: npm run test:e2e

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: jest-html-reports
          path: reports/*.html