name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Unit-Tests (JUnit-Output)
        run: npm test -- --runInBand --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: jest-junit.xml
          CI: true

      - name: 📊 Test-Report veröffentlichen
        uses: actions/upload-test-report@v1
        with:
          name: Jest Unit Tests
          path: jest-junit.xml

      - name: E2E-Tests mit Puppeteer
        run: npm run test:e2e -- --runInBand --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: e2e-junit.xml
          CI: true

      - name: 📊 E2E-Test-Report veröffentlichen
        uses: actions/upload-test-report@v1
        with:
          name: Jest E2E Tests
          path: e2e-junit.xml
