name: CI

on:
  push:       # läuft auf jeden Push, nicht nur main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Abhängigkeiten installieren
        run: npm install

      # Puppeteer native libs (Linux)
      - name: System-Dependencies für Puppeteer
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-6 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libxss1

      # Unit- und Logic-Tests inkl. HTML-Report
      - name: Unit-Tests mit HTML-Report
        run: |
          # wir nutzen jest-html-reporter
          npm test -- --reporters=default --reporters=jest-html-reporter
        env:
          CI: true

      - name: Sammle HTML-Report
        if: always()
        run: mkdir -p reports
      - name: Verschiebe HTML-Report
        if: always()
        run: mv jest-html-report.html reports/

      - name: Upload HTML-Report als Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-html-report
          path: reports/

      # End-to-End Tests mit Puppeteer
      - name: E2E-Tests mit Puppeteer
        run: npm run test:e2e

      - name: Upload E2E-Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-logs
          path: |
            tests/e2e/*.log
            puppeteer_debug.log
