name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Abhängigkeiten installieren
        run: npm install

      - name: System-Dependencies für Puppeteer
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-6 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libxss1

      - name: Unit-Tests mit HTML-Report
        run: |
          npm test -- --reporters=default --reporters=jest-html-reporter
        env:
          CI: true

      - name: Sammle HTML-Report
        if: always()
        run: |
          mkdir -p reports
          mv jest-html-report.html reports/

      - name: Upload HTML-Report als Artifact
        if: always()
        uses: actions/upload-artifact    # <-- hier auf v2 zurückgestuft
        with:
          name: jest-html-report
          path: reports/

      - name: E2E-Tests mit Puppeteer
        run: npm run test:e2e

      - name: Upload E2E-Logs
        if: failure()
        uses: actions/upload-artifact   # <-- und hier ebenfalls v2
        with:
          name: e2e-logs
          path: tests/e2e/*.log
