name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Abhängigkeiten installieren
        run: npm ci

      # Falls Puppeteer native libs braucht:
      - name: System-Dependencies für Puppeteer
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-6 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnss3 \
            libxss1

      - name: Unit- und Logic-Tests
        run: npm test

      - name: End-to-End Tests mit Puppeteer
        run: npm run test:e2e
